<package format="3">
  <name>virtual_camera</name>
  <version>0.0.0</version>
  <description>A minimalistic Rust-based implementation of an image publisher and subscriber</description>
  <maintainer email="beyhy94@gmail.com">user</maintainer>
  <license>Apache 2.0</license>

  <depend>rclrs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>