name: Coveralls CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
          CCACHE_DIR: /github/home/.ccache
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base-jammy
    steps:
      - name: Build colcon tools
        run: |
          sudo apt-get update && \
            sudo apt-get install -y curl && \
            sudo sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list' && \
            sudo curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add - && \
            sudo apt update && \
            sudo apt install python3-colcon-common-extensions

      - name: Build your ROS 2 package
        run: |
          colcon build