name: Coveralls CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    container:
      image: ros:humble-perception-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script
        run: |
          chmod +x ./ci.sh
          ./ci.sh

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-file: ./lcov/total_coverage.info
