name: Coveralls CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - name: Build colcon tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install -U colcon-common-extensions
      - name: Build your ROS 2 package
        run: |
          colcon build
