name: Coveralls CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build colcon tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo apt-get install -y  ament-cmake ament-index-cpp
          pip install -U colcon-common-extensions

      - name: Download ROS 2 dependencies
        run: |
          rosdep update
          rosdep install -y --from-paths ./ --ignore-src \
          --rosdistro humble

      - name: Build your ROS 2 package
        run: |
          pwd
          colcon build
