name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ROS dependencies
        run: |
          sudo apt update && sudo apt install -y ros-$ROS_DISTRO-colcon-cd ros-$ROS_DISTRO-test-results lcov

      - name: Colcon workspace setup
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon build --symlink-install --cmake-args -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'

      - name: Run tests with coverage
        run: |
          colcon lcov-result --initial
          colcon test --packages-select virtual_camera
          colcon lcov-result

      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      
      - name: Upload coverage to Coveralls
        uses: coveralls-actions/coveralls-action@v1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-coverage: ./lcov/