name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble, ROS_REPO: testing}
          - {ROS_DISTRO: humble, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

      - name: Install ROS 2 dependencies (modify as needed)
        run: |
          sudo apt update && sudo apt install -y \
            python3-colcon-common-extensions \
            python3-colcon-ridl \
            python3-rclpy

      - name: Setup ROS 2 environment (modify as needed)
        run: |
          source /opt/ros/humble/setup.bash

      - name: Build your ROS 2 package (modify as needed)
        run: |
          colcon build --symlink-install --cmake-args \
            -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' \
            -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'

      - name: Run ROS 2 unit tests with coverage (modify as needed)
        run: |
          colcon lcov-result --initial && \
            colcon test --packages-select virtual_camera
            colcon lcov-result

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-file: ./lcov/total_coverage.info
